### ISSUE TITLE
[New entry]: packages.sury.org

### ISSUE THREAD

**Issue by SagePtr** [toxic-repos/toxic-repos#117]
# Required parameters

**Name of protestware (name)**: <br>https://packages.sury.org/<br>

**Link to evidence (commit_link)**: <br>https://github.com/oerdnj/deb.sury.org/issues/2155<br>
![image](https://github.com/user-attachments/assets/70a958a8-f004-465c-b755-aac305058648)

**Justification for changes (description)**: <br>Чешский нацист по имени Ондрей Суржик. Делает сборки PHP под Debian и Ubuntu. Заблокировал доступ к своему репозиторию с российских IP, а также из шведской локации VPS Aeza (раньше блок IP принадлежал провайдеру VDSina, потому тоже попал под раздачу). Через браузер его репозиторий https://packages.sury.org/ открывается нормально, а через менеджер пакетов apt (для которого он предназначен) не работает из-за нестандартного кода ответа сервера 451. Также переблочил в своём github-репозитории российских коллабораторов, отобрав доступ к созданию issue и пулреквестов, а также комментированию.<br>

**Type of entry (problem_type)**: <br>IP blocking, Broken assembly<br>

# Additional parameters

**Date of detection**: <br>2 Jul 2024<br>

**Date of discreditation (datetime)**: <br>2 Jul 2024<br>

**PURL**: <br>(не в курсе, как это составлять)<br>
> [!NOTE]
> Usually the name of the package and developer in the package manager is different from the name of the project and repository in Github

**Comment by sergiomarotco** [comment]
Завтра

**Comment by sergiomarotco** [comment]
@oerdnj FYI

**Comment by oerdnj** [comment]
Thank you. Proud to be listed!

**Comment by sergiomarotco** [comment]
#124

**Comment by sergiomarotco** [comment]
the worst thing to be proud of

**Comment by SagePtr** [comment]
> Thank you. Proud to be listed!

"I'm assh*le and I know it"? BTW, you blocked access not only from Russia, but from Sweden also, at Aeza VPS, breaking docker containers under this non-russian VPS which rely on your repo. But Russians can just change your repo URL to any mirror, we are under sanctions few years and can easily evade your stupid ban, but legit users suffer because of your arrogance. And not only did this, but also geoblocked me from your repo and prevented to file an issue about excessive blocking which affects Sweden. Assh*le move, isn't it?
