### ISSUE TITLE
Remove Hogwarts Legacy

### ISSUE THREAD

**Issue by hogsmead** [toxic-repos/toxic-repos#121]
What does a proprietary video game have to do with open source?

**Comment by akopachov** [comment]
Looks like this repo is no longer just about "code of varying degrees of danger to popular Open Source projects" as [README claims](https://github.com/toxic-repos/toxic-repos/blob/020f6de5acfda23208d2d6a98e1e72834b67804f/README.md?plain=1#L13) but instead it becomes a place where maintainer tracks anything that is not in align with russian propaganda.

In Hogwarts Legacy there is no Russian translation, but there is Ukrainian one, so russian propaganda and author assumes this is rusophobic and hence maintainer tracks it here.

There are a lot of websites in this list that have Ukranian flag in there, and this is enough for the Russian propaganda and maintainer to assume such a websites as rusophobic.

**Comment by sergiomarotco** [comment]
@hogsmead hi, the tag for this application is “hostile_actions”. U can using other tags, for example “malware”.

**Comment by sergiomarotco** [comment]
@hogsmead Sounds right, but today the repository is mostly popular in the Russian-speaking segment. There are no proposals to include descredential actions in relation to other countries. We record any hostile actions and classify them. So far, there is no goal to remove non-open-source projects.

If you use this repository in your work, you can ignore records that are not interesting to you.

**Comment by drizt** [comment]
How hostile actions in proprieatary soft discredit open-source? You again do not answer on initial question.
