### ISSUE TITLE
[New entry]: russian-related toxic repos

### ISSUE THREAD

**Issue by akopachov** [toxic-repos/toxic-repos#123]
# Required parameters

**Name of protestware (name)**: <br><br>
https://github.com/mermakowich/spaceZZZ
https://github.com/mermakowich/GOYDA-ZOV
https://github.com/ILK17/zov

**Link to evidence (commit_link)**: <br><br>
https://github.com/mermakowich/spaceZZZ/commit/8ab527f1c9e52b186f43575e740f73a4dd97dd5d
https://github.com/ILK17/zov/commit/f0de3242fad6ceb33bce2c08c799138a5a2faa93

**Justification for changes (description)**: <br><br>
According to this repo, political slogans are unacceptable in open-source repos regardless of their source and topics.

**Type of entry (problem_type)**: <br><br>
Political slogan

# Additional parameters

**Date of detection**: <br><br>
30.08.2024

**Date of discreditation (datetime)**: <br><br>
30.08.2024

**PURL**: <br><br>
> [!NOTE]
> Usually the name of the package and developer in the package manager is different from the name of the project and repository in Github

**Comment by sergiomarotco** [comment]
#124
