### ISSUE TITLE
Заменить разделитель CSV с "," на "|"

### ISSUE THREAD

**Issue by sergiomarotco** [toxic-repos/toxic-repos#86]
В поле description содержатся различные знаки табуляции, переносы строки, которые при просмотре CSV не дают возможность разбить текст на нормальные столбцы

**Comment by bannndi** [comment]
Почему не на Tab ?

**Comment by sergiomarotco** [comment]
> Почему не на Tab ?

Потому что в description так же может быть как tab так и перенос строки:
![image](https://user-images.githubusercontent.com/29877074/195815632-e8b0cbd3-ea5a-4186-9477-3aa897d9dafc.png)

**Comment by bannndi** [comment]
Ясно. Раньше tab казался самым безопасным разделителем. Так скоро и | пайп станут юзать в тексте )

**Comment by Maligosus** [comment]
Мне одно интересно, что тебе сделали плохого сайты с обычными банерами. (P.S. чтобы тебе не мерещались биолаборатории и укрофашисты, я если что из России).

**Comment by stravnik** [comment]
@Maligosus Мы на "ты" не переходили.
А позицию по сайтам с баннерами я уже освещал и не один раз.
P.S. Не стоит нарушать [CODE_OF_CONDUCT.md](https://github.com/stravnik/toxic-repos/blob/main/CODE_OF_CONDUCT.md) репозитория.

**Comment by LEv145** [comment]
Как по мне проблема не в разделители, а в создании csv
Пример проблемы с разделителем в википедии:
```
1997,Ford,E350,"ac, abs, moon",3000.00
1999,Chevy,"Venture «Extended Edition»","",4900.00
1996,Jeep,Grand Cherokee,"MUST SELL! air, moon roof, loaded",4799.00
```
Тут используются кавычки

**Comment by sergiomarotco** [comment]
> Как по мне проблема не в разделители, а в создании csv Пример проблемы с разделителем в википедии:
> 
> ```
> 1997,Ford,E350,"ac, abs, moon",3000.00
> 1999,Chevy,"Venture «Extended Edition»","",4900.00
> 1996,Jeep,Grand Cherokee,"MUST SELL! air, moon roof, loaded",4799.00
> ```
> 
> Тут используются кавычки
> 
> Что я реализовано ![изображение](https://user-images.githubusercontent.com/40071054/201374521-1ea6a832-4c95-49a0-aba4-eb4f7ddfaf82.png)
> 
> Поэтому это скорее проблема клиента, тк всё по стандарту, github читает нормально, как и libre office ![изображение](https://user-images.githubusercontent.com/40071054/201404189-d6fd822a-4d8b-4974-9fb2-8238b5393b3f.png)
> 
> Аналогично с табами и др., это проблема клиента, пусть будет однородно всё, как и с sql

ок, так как мне разбить на столбцы ваш файл в excel?

**Comment by sergiomarotco** [comment]
Заменил на пробелы
