### ISSUE TITLE
Вопрос по охвату списка

### ISSUE THREAD

**Issue by dartraiden** [toxic-repos/toxic-repos#97]
Чтобы сразу расставить точки над ё и не создавать пуллреквесты впустую: в список принимаются вообще любые продукты, которые политизируют опенсорс и подрывают к нему доверие? Условно говоря, если разработчик взял и понапихал на сайт "ZOV" и понатыкал в код закладок, которые совершают деструктивные действия, будучи запущенными, скажем, в странах НАТО, это годится или нет?

**Comment by stravnik** [comment]
@dartraiden Если код совершает деструктивные/политические/и прочие нежелательные действия, то присылайте PR. С большим удовольствием добавлю такие репы в список.
